export const menuList = [
  {
    en: 'Events',
    ru: 'События',
    es: 'Eventos',
    it: 'Eventi',
    de: 'Veranstaltungen',
    fr: 'Événements',
    sw: 'Händelser',
    pl: 'Wydarzenia',
  },
  {
    en: 'Home',
    ru: 'Главная',
    es: 'Hogar',
    it: 'Casa',
    de: 'Heim',
    fr: 'Maison',
    sw: 'Hem',
    pl: 'Dom',
  },
  {
    en: 'Shop',
    ru: 'Магазин',
    es: 'Comercio',
    it: 'Negozio',
    de: 'Geschäft',
    fr: 'Boutique',
    sw: 'Handla',
    pl: 'Sklep',
  },
  {
    en: 'Cart',
    ru: 'Корзина',
    es: 'Cesta',
    it: 'Carrello',
    de: 'Warenkorb',
    fr: 'Panier',
    sw: 'Vagn',
    pl: 'Wózek',
  },
  {
    en: 'Account',
    ru: 'Аккаунт',
    es: 'Cuenta',
    it: 'Account',
    de: 'Konto',
    fr: 'Compte',
    sw: 'Konto',
    pl: 'Konto',
  },
  {
    en: 'Change avatar',
    ru: 'Изменить аватар',
    es: 'Cambiar avatar',
    it: 'Cambia avatar',
    de: 'Avatar ändern',
    fr: 'Changer avatar',
    sw: 'Byt avatar',
    pl: 'Zmień awatar',
  },
  {
    en: 'Save',
    ru: 'Сохранить',
    es: 'Ahorrar',
    it: 'Salva',
    de: 'Speichern',
    fr: 'Sauvegarder',
    sw: 'Spara',
    pl: 'Ratować',
  },
  {
    en: 'Change',
    ru: 'Изменить',
    es: 'Cambiar',
    it: 'Modifica',
    de: 'Ändern',
    fr: 'Changement',
    sw: 'Ändra',
    pl: 'Zmiana',
  },
  {
    en: 'Your Name',
    ru: 'Ваше имя',
    es: 'Su nombre',
    it: 'Il tuo nome',
    de: 'Ihr Name',
    fr: 'Votre nom',
    sw: 'Ditt namn',
    pl: 'Twoje imię',
  },
  {
    en: 'Choose Language',
    ru: 'Выберите язык',
    es: 'Seleccionar idioma',
    it: 'Scegli la lingua',
    de: 'Sprache auswählen',
    fr: 'Choisir la langue',
    sw: 'Välj Språk',
    pl: 'Wybierz język',
  },
  {
    en: 'Name should contain atleast 3 character',
    ru: 'Имя должно содержать не менее 3 символов.',
    es: 'El nombre debe contener al menos 3 caracteres.',
    it: 'Il nome deve contenere almeno 3 caratteri',
    de: 'Der Name muss mindestens 3 Zeichen enthalten',
    fr: 'Le nom doit contenir au moins 3 caractères',
    sw: 'Namnet bör innehålla minst 3 tecken',
    pl: 'Nazwa powinna zawierać co najmniej 3 znaki',
  },
  {
    en: 'Order',
    ru: 'Заказ',
    es: 'Orden',
    it: 'Ordine',
    de: 'Befehl',
    fr: 'Commande',
    sw: 'Beställa',
    pl: 'Zamówienie',
  },
  {
    en: 'Sub Total',
    ru: 'Подытог',
    es: 'Subtotal',
    it: 'Subtotale',
    de: 'Zwischensumme',
    fr: 'Sous-total',
    sw: 'Subtotal',
    pl: 'Podsuma',
  },
  {
    en: 'Tax',
    ru: 'Налог',
    es: 'Impuesto',
    it: 'Tassare',
    de: 'Steuer',
    fr: 'Impôt',
    sw: 'Beskatta',
    pl: 'Podatek',
  },
  {
    en: 'Total Amount',
    ru: 'Общая сумма',
    es: 'Importe total',
    it: 'Importo totale',
    de: 'Gesamtbetrag',
    fr: 'Montant total',
    sw: 'Totalt belopp',
    pl: 'Całkowita kwota',
  },
  {
    en: 'Apply',
    ru: 'Применять',
    es: 'Aplicar',
    it: 'Aplicar',
    de: 'Anwenden',
    fr: 'Appliquer',
    sw: 'Tillämpas',
    pl: 'Stosować',
  },
  {
    en: 'Place Order',
    ru: 'Разместить заказ',
    es: 'Realizar pedido',
    it: "Effettuare l'ordine",
    de: 'Bestellung aufgeben',
    fr: 'Passer une commande',
    sw: 'Lägg beställning',
    pl: 'Złóż zamówienie',
  },
  {
    en: 'Promo Code',
    ru: 'Промо-код',
    es: 'Código promocional',
    it: 'Codice promozionale',
    de: 'Aktionscode',
    fr: 'Code promotionnel',
    sw: 'Kampanjkod',
    pl: 'Kod promocyjny',
  },
  {
    en: 'Show this code to the waiter',
    ru: 'Покажите этот код официанту',
    es: 'Muestra este código al camarero.',
    it: 'Mostra questo codice al cameriere',
    de: 'Zeigen Sie diesen Code dem Kellner',
    fr: 'Montrez ce code au serveur',
    sw: 'Visa denna kod för servitören',
    pl: 'Pokaż ten kod kelnerowi',
  },
  {
    en: 'salads',
    ru: 'салаты',
    es: 'ensaladas',
    it: 'insalate',
    de: 'salate',
    fr: 'insalate',
    sw: 'sallader',
    pl: 'sałatki',
  },
  {
    en: 'starters',
    ru: 'закуски',
    es: 'Entrantes',
    it: 'antipasti',
    de: 'Vorspeisen',
    fr: 'entrées',
    sw: 'förrätter',
    pl: 'przystawki',
  },
  {
    en: 'desserts',
    ru: 'десерты',
    es: 'postres',
    it: 'dolci',
    de: 'Nachspeisen',
    fr: 'desserts',
    sw: 'desserter',
    pl: 'hello',
  },
  {
    en: 'drinks',
    ru: 'напитки',
    es: 'bebidas',
    it: 'bevande',
    de: 'Getränke',
    fr: 'boissons',
    sw: 'drycker',
    pl: 'hello',
  },
  {
    en: 'All',
    ru: 'Все',
    es: 'Todo',
    it: 'Tutto',
    de: 'Toute',
    fr: 'Alle',
    sw: 'Alla',
    pl: 'Wszystko',
  },
  {
    en: 'Select category',
    ru: 'Выберите категорию',
    es: 'Seleccionar categoría',
    it: 'Seleziona la categoria',
    de: 'Kategorie wählen',
    fr: 'Sélectionnez une catégorie',
    sw: 'Välj kategori',
    pl: 'Wybierz kategorię',
  },
  {
    en: 'Add',
    ru: 'Добавить',
    es: 'Agregar',
    it: 'Aggiungere',
    de: 'Hinzufügen',
    fr: 'Ajouter',
    sw: 'Tillägga',
    pl: 'Dodać',
  },
  {
    en: 'Added',
    ru: 'Добавлено',
    es: 'Agregado',
    it: 'Aggiunto',
    de: 'Hinzugefügt',
    fr: 'Ajouté',
    sw: 'Tillagd',
    pl: 'W dodatku',
  },
  {
    en: 'Broadcasts',
    ru: 'Трансляции',
    es: 'Transmisiones',
    it: 'Trasmissioni',
    de: 'Sendungen',
    fr: 'Diffusions',
    sw: 'Sändningar',
    pl: 'Transmisje',
  },
  {
    en: 'Your cart is empty',
    ru: 'Ваша корзина пуста',
    es: 'Tu carrito está vacío',
    it: 'Il tuo carrello è vuoto',
    de: 'Ihr Warenkorb ist leer',
    fr: 'Votre panier est vide',
    sw: 'Din varukorg är tom',
    pl: 'Twój koszyk jest pusty',
  },
  {
    en: 'Booking',
    ru: 'Резерв столика',
    es: 'Reserva de mesa',
    it: 'Prenotazione tavolo',
    de: 'Tischreservierung',
    fr: 'Réservation de table',
    sw: 'Bokning',
    pl: 'Rezerwacja',
  },
  {
    en: 'Select date',
    ru: 'Выберите дату',
    es: 'Seleccionar fecha',
    it: 'Seleziona la data',
    de: 'Datum auswählen',
    fr: 'Sélectionnez une date',
    sw: 'Välj datum',
    pl: 'Wybierz datę',
  },
  {
    en: 'Select time',
    ru: 'Выберите время',
    es: 'Seleccione la hora',
    it: "Seleziona l'ora",
    de: 'Wähle eine Uhrzeit',
    fr: "Sélectionnez l'heure",
    sw: 'Välj tid',
    pl: 'Wybierz czas',
  },
  {
    en: 'Continue',
    ru: 'Продолжить',
    es: 'Continuar',
    it: 'Continuare',
    de: 'Weitermachen',
    fr: 'Continuer',
    sw: 'Fortsätta',
    pl: 'Kontynuować',
  },
  {
    en: 'Book now',
    ru: 'Забронировать',
    es: 'Libro',
    it: 'Libro',
    de: 'Buch',
    fr: 'Réserve',
    sw: 'Boka nu',
    pl: 'Zarezerwuj teraz',
  },
  {
    en: 'Your phone',
    ru: 'Ваш телефон',
    es: 'Tu teléfono',
    it: 'Il tuo telefono',
    de: 'Ihr Telefon',
    fr: 'Votre téléphone',
    sw: 'Din telefon',
    pl: 'Twój telefon',
  },
  {
    en: 'E-mail',
    ru: 'E-mail',
    es: 'E-mail',
    it: 'E-mail',
    de: 'E-mail',
    fr: 'E-mail',
    sw: 'E-mail',
    pl: 'E-mail',
  },
  {
    en: 'On this page you can book a table for the date you are interested in.',
    ru: 'На этой странице вы можете забронировать столик на интересующую вас дату.',
    es: 'En esta página podrás reservar mesa para la fecha que te interese.',
    it: 'In questa pagina puoi prenotare un tavolo per la data che ti interessa.',
    de: 'Auf dieser Seite können Sie einen Tisch für den von Ihnen gewünschten Termin reservieren.',
    fr: 'Sur cette page, vous pouvez réserver une table pour la date qui vous intéresse.',
    sw: 'På denna sida kan du boka bord för det datum du är intresserad av.',
    pl: 'Na tej stronie możesz zarezerwować stolik na interesujący Cię termin.',
  },
  {
    en: 'Fill out a simple form and our managers will contact you shortly.',
    ru: 'Заполните простую форму и наши менеджеры свяжутся с вами в ближайшее время.',
    es: 'Complete un sencillo formulario y nuestros gerentes se comunicarán con usted en breve.',
    it: 'Compila un semplice modulo e i nostri responsabili ti contatteranno al più presto.',
    de: 'Füllen Sie ein einfaches Formular aus und unsere Manager werden Sie in Kürze kontaktieren.',
    fr: 'Remplissez un simple formulaire et nos gestionnaires vous contacteront sous peu.',
    sw: 'Fyll i ett enkelt formulär så kontaktar våra chefer dig inom kort.',
    pl: 'Wypełnij prosty formularz, a nasi menedżerowie wkrótce się z Tobą skontaktują.',
  },
  {
    en: 'Your table has been successfully booked!',
    ru: 'Ваш столик успешно забронирован!',
    es: '¡Su mesa ha sido reservada con éxito!',
    it: 'Il tuo tavolo è stato prenotato con successo!',
    de: 'Ihr Tisch wurde erfolgreich reserviert!',
    fr: 'Votre table a été réservée avec succès !',
    sw: 'Ditt bord har bokats!',
    pl: 'Twój stolik został pomyślnie zarezerwowany!',
  },
  {
    en: 'Our managers will contact you shortly.',
    ru: 'Наши менеджеры свяжутся с вами в ближайшее время.',
    es: 'Nuestros responsables se pondrán en contacto con usted en breve.',
    it: 'I nostri responsabili ti contatteranno a breve.',
    de: 'Unsere Manager werden sich in Kürze mit Ihnen in Verbindung setzen.',
    fr: 'Nos responsables vous contacteront sous peu.',
    sw: 'Våra chefer kommer att kontakta dig inom kort.',
    pl: 'Nasi menedżerowie wkrótce się z Tobą skontaktują.',
  },
  {
    en: 'Pizza Making Master Class',
    ru: 'Мастер-класс по приготовлению пиццы',
    es: 'Clase magistral de elaboración de pizza',
    it: 'Masterclass sulla preparazione della pizza',
    de: 'Meisterkurs zum Pizzabacken',
    fr: 'Master class de préparation de pizza',
    sw: 'Masterklass för pizzatillverkning',
    pl: 'Kurs mistrzowski robienia pizzy',
  },
  {
    en: "Children's Mini-Football Championship",
    ru: 'Чемпионат по десткому мини-футболу',
    es: 'Campeonato de minifútbol infantil',
    it: 'Campionato di calcetto infantile',
    de: 'Mini-Fußballmeisterschaft für Kinder',
    fr: 'Championnat de mini-football pour enfants',
    sw: 'Barnmästerskap i minifotboll',
    pl: 'Mistrzostwa Dzieci w Mini Piłce Nożnej',
  },
  {
    en: 'Sports: Legends and Myths',
    ru: 'Спорт: Легенды и Мифы',
    es: 'Deportes: Leyendas y Mitos',
    it: 'Sport: leggende e miti',
    de: 'Sport: Legenden und Mythen',
    fr: 'Sports: légendes et mythes',
    sw: 'Sport: Legender och myter',
    pl: 'Sport: legendy i mity',
  },
  {
    en: 'Football evening',
    ru: 'Футбольный вечер',
    es: 'Noche de fútbol',
    it: 'Serata di calcio',
    de: 'Fußballabend',
    fr: 'Soirée foot',
    sw: 'Fotbollskväll',
    pl: 'Wieczór piłkarski',
  },
  {
    en: "Let's cook a delicious Mexican taco",
    ru: 'Готовим вкусный мексиканский тако',
    es: 'Cocinar deliciosos tacos mexicanos',
    it: 'Cucinare deliziosi tacos messicani',
    de: 'Köstliche mexikanische Tacos kochen',
    fr: 'Cuisiner de délicieux tacos mexicains',
    sw: 'Lagar läckra mexikanska tacos',
    pl: 'Gotowanie pysznych meksykańskich tacos',
  },
  {
    en: 'Auto racing 2024 Rally',
    ru: 'Автогонки 2024 Ралли',
    es: 'Rally de carreras de autos 2024',
    it: 'Corse automobilistiche Rally 2024',
    de: 'Autorennen-Rallye 2024',
    fr: 'Rallye de course automobile 2024',
    sw: 'Autoracing 2024 Rally',
    pl: 'Rajd wyścigów samochodowych 2024',
  },
  {
    en: "Lecture 'Healthy Nutrition'",
    ru: "Лекция 'Здоровое питание'",
    es: "Conferencia 'Alimentación saludable'",
    it: "Conferenza 'Mangiare sano'",
    de: "Vortrag 'Gesunde Ernährung'",
    fr: "Conférence 'Alimentation saine'",
    sw: "Föreläsning 'Hälsosam kost'",
    pl: "Wykład 'Zdrowe odżywianie'",
  },
  {
    en: 'master class',
    ru: 'мастер-класс',
    es: 'clase magistral',
    it: 'lezione magistrale',
    de: 'Meisterklasse',
    fr: 'classe de maître',
    sw: 'mästarklass',
    pl: 'klasa mistrzowska',
  },
  {
    en: 'watching races',
    ru: 'просмотр гонок',
    es: 'viendo carreras',
    it: 'guardare le gare',
    de: 'Rennen schauen',
    fr: 'regarder des courses',
    sw: 'tittar på lopp',
    pl: 'oglądanie wyścigów',
  },
  {
    en: 'lecture from a nutritionist',
    ru: 'лекция от нутрициолога',
    es: 'conferencia de un nutricionista',
    it: 'conferenza di un nutrizionista',
    de: 'Vortrag eines Ernährungsberaters',
    fr: "conférence d'un nutritionniste",
    sw: 'föreläsning från en dietist',
    pl: 'wykład dietetyka',
  },
];
